### ISSUE TITLE
exception BAH

### ISSUE THREAD

**Issue by umiterkol** [fopina/syncme_exposed#2]
$python syncme.py +31684525254
No token found, registering...

Traceback (most recent call last):
  File "syncme.py", line 115, in <module>
    s.register('351932123123')
  File "syncme.py", line 32, in register
    r = self._call('register_2',params)
  File "syncme.py", line 68, in _call
    raise Exception('BAH')
Exception: BAH

**Comment by fopina** [comment]
This is no longer maintained.
I’ll update the README to reflect it and archive the repo
